### PR TITLE
Feature/new partner logos

### PR DESCRIPTION
**Pull request by felskia**

### CODE REVIEW

**Comment by felskia** [comment]
@dereklieu I'm not quite sure what's going on here. Could you take a look for me? I just wanted to changed the logos at the bottom for Hagar. 

Thanks

**Comment by DylanMoriarty** [comment]
@felskia it looks like you PR'd from the Map Yemen repo to here, which _also_ grabbed all the commits we had made to translate the site. I can hit this for you in the morning.

Is this an update to Map-Egypt, Map-Yemen, or both for the footer images?

**Comment by dereklieu** [comment]
Ah yeah, forks automatically redirect new pull requests to the original repo. You'll want to re-open this pull request but change the "base" dropdown to the develop branch of map-yemen.

Closing this, otherwise it would turn map-egypt into map-yemen :D

**Comment by felskia** [comment]
@DylanMoriarty @dereklieu ok... maybe I didn't look at where things are pulling from but can we change that instead of closing the PR? I still want these logos that I changed to be pushed to the Yemen site.

**Pull request closed without merging**
