### PR TITLE
Project pages

### LINKED ISSUE #13: Make main navigation links functional

### PR DESCRIPTION
**Pull request by dereklieu**
Close #13 fix nav links
Shows mock project cards on projects page
Fixes modal
Includes chart code that isn't rendering yet

### CODE REVIEW

**Comment by dereklieu** [comment]
@kamicut can you give this a 👀 and merge?

**Comment by kamicut** [comment]
I'm seeing something weird in the project list header rendering: 



Is this expected?

**Comment by dereklieu** [comment]
Yeah this needs some styling attn @ascalamogna - I basically took the entire element from `/en/elements` and put it into a module.

**Comment by kamicut** [comment]
Ok, LGTM then 👍

**Pull request merged**
