### PR TITLE
close #313; force Arabic date format when in Arabic view

### LINKED ISSUE #313: Changing the date to be Month/Day/Year
All dates on the site

### PR DESCRIPTION
**Pull request by nbumbarger**
Defaulting to locale-based date format only works when the browser's locale is set. This fix forces Arabic date formatting when the Arabic view is turned on, regardless of user settings.

### CODE REVIEW

**Comment by felskia** [comment]
@nbumbarger so it still looks wrong. Looks like it's year, month, day?

screen shot 2017-04-06 at 3 38 54 pm

**Comment by nbumbarger** [comment]
@felskia yes, that's the format I read was preferred in Arabic. Did you want yyyy/d/m?

**Comment by felskia** [comment]
@nbumbarger that is because it's right to left. So on the English side it would be: dd/mm/yyyy and on the Arabic side it would be yyyy/mm/dd

**Comment by nbumbarger** [comment]
The latest change makes it so that the Arabic and English views always show dates as yyyy/d/m and the English view m/d/yyyy, respectively.

**Comment by felskia** [comment]
@nbumbarger sorry for the confusion here. The problem now is that it's back to what it was. Day should be first. So it should be:

English: Day/Month/Year
Arabic: Year/Month/Day

**Comment by nbumbarger** [comment]
updated

**Pull request merged**
