### PR TITLE
Fix translation issues

### LINKED ISSUE #284: Arabic text - not showing up
There are three issues on the arabic side. 

Text not showing up in Arabic or links not working
- This is an example: https://map-egypt.github.io/#/en/projects/13f7fd00-a53f-4566-a771-f9de5f73fc81?_k=u3v3uy. I believe the local manager is the missing one
- The link for the ministry isn't working on the arabic side

Also, if there is no Arabic text, there should instead just be English. I'll check to see if it's happening on other pages. 

Finally, if you're in Arabic and click to a donor page, the graph doesn't show up below the big stat numbers. If you click to English and then press refresh it does. 

@dereklieu @nbumbarger anyone have time to fix this bug tomorrow?

### PR DESCRIPTION
**Pull request by dereklieu**
Close #284 

1. Ministry links work on both languages
2. Owner/local manager shows up on both languages
3. Fix issue of some charts not rendering on Arabic
4. Summary items show the correct language

On the last point: some parts lower in the page (charts, project cards) will "fall back" to English if on Arabic pages and Arabic doesn't exit. These would look totally broken otherwise. But the top-level items (donor name, category name) will attempt to show the right language or show nothing.

This should give the admins a good indication of which items still need translations.

### CODE REVIEW

**Comment by felskia** [comment]
@dereklieu Looks good except for one thing... 

- unit on the backend for "Farm-level irrigation modernization" is filled in in Arabic but it shows up as English.

**Comment by dereklieu** [comment]
@felskia hm, just checked that and didn't see a translation for the project name. Possible Hagar tried to change it and deleted it?

**Comment by felskia** [comment]
@dereklieu It's not the project name but under beneficiaries it is the unit. So here it is "Small-scale farmers" but the unit in Arabic doesn't show.

**Comment by dereklieu** [comment]
@felskia ah, got it. Fixed in the latest push. 

screen shot 2017-02-22 at 7 53 38 pm

**Pull request merged**
