### PR TITLE
Add donors

### PR DESCRIPTION
**Pull request by ascalamogna**
@dereklieu @felskia I think this is really all we can do for the donor pages with the current data.

### CODE REVIEW

**Comment by felskia** [comment]
@ascalamogna I just have a few styling things that might make it feel a little tighter. Let me know if I should comment here or in tickets. 

Thanks!

**Comment by ascalamogna** [comment]
@felskia listing them here is fine.

**Comment by felskia** [comment]
@ascalamogna ok, the small tweaks I see here are: 

- On this page the header is actually much lower on the page then on other pages, like the project page. I would make this the same. This will also make the share button align in the same way. 
- Make the space below the header smaller. I think if we half the amount of white space between the header and the grey area it will make it look less empty. 
- Area the has the map - the bottom margin is larger than the margin on the other sides
- Crazy idea... but maybe something to try. If there is only one project maybe we make the map bigger width wise and then instead of having the numbers side by side they are below each other? 
(if this doesn't work then I say we just run with what we have). 

Thanks!!

**Comment by ascalamogna** [comment]
@dereklieu this should be good to merge now

**Comment by felskia** [comment]
@ascalamogna one last thing here that I didn't catch before. In your comps you have the map aligned with the edge of the box. What are your thoughts here? Might be nice but on the project page, it might get a little long. Did like the look of it in the comps so maybe we try and figure out how to make it work? If you do align it with the edge make sure to put the grey line on the right hand side. 

Thanks!

**Pull request merged**
